[[ISSUERS]]
address = "rDpGBpeq4NkgWk7xneFKCQDVBNwPe5jWqb"
name = "LionArt"

[[TOKENS]]
issuer = "rDpGBpeq4NkgWk7xneFKCQDVBNwPe5jWqb"
currency = "AxRT"
name = "Hearts"
desc = "With the LionArt Crypto Token, we aim to create a sustainable funding model for artists and foster the growth of the digital art community."
icon = "https://www.axrt.space/axrt_icon-png"

[[TOKENS.WEBLINKS]]
url = "https://www.axrt.space"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.axrt.space/nft-gallery"
type = "website"
title = "Token Info Dashboard"
