[[ACCOUNTS]]
address = "rDpGBpeq4NkgWk7xneFKCQDVBNwPe5jWqb"
network = "main"
desc = "AxRT issuer account."

[[ACCOUNTS]]
address = "rpncNpj8fDgn6EKRLQJLYDVrhp5dufuDeV"
network = "main"
desc = "AYA issuer account."

[[ACCOUNTS]]
address = "r4jQyhyUH2tzL5HGh1Ph8hMubskLgbgNvN"
network = "main"
desc = "AxRT/AYA treasury and distribution account."

[[ISSUERS]]
address = "rDpGBpeq4NkgWk7xneFKCQDVBNwPe5jWqb"
name = "Etincelles"

[[ISSUERS]]
address = "rpncNpj8fDgn6EKRLQJLYDVrhp5dufuDeV"
name = "Allay Protocol"

[[CURRENCIES]]
code = "AxRT"
issuer = "rDpGBpeq4NkgWk7xneFKCQDVBNwPe5jWqb"
name = "LionArt"
desc = "With the LionArt Crypto Token, we aim to create a sustainable funding model for artists and foster the growth of the digital art community."

[[CURRENCIES]]
code = "AYA"
issuer = "rpncNpj8fDgn6EKRLQJLYDVrhp5dufuDeV"
name = "Allay"
desc = "Companion ecosystem token for the AxRT platform."

[[TOKENS.WEBLINKS]]
url = "https://www.axrt.space"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.axrt.space/nft-gallery"
type = "whitepaper"
title = "Project Whitepaper"
