[[ACCOUNTS]]
address = "rDpGBpeq4NkgWk7xneFKCQDVBNwPe5jWqb"
network = "main"
desc = "AxRT issuer account."

[[ACCOUNTS]]
address = "r4jQyhyUH2tzL5HGh1Ph8hMubskLgbgNvN"
network = "main"
desc = "AxRT treasury and distribution account."

[[ISSUERS]]
address = "rDpGBpeq4NkgWk7xneFKCQDVBNwPe5jWqb"
name = "Etincelles"

[[TOKENS]]
issuer = "rDpGBpeq4NkgWk7xneFKCQDVBNwPe5jWqb"
currency = "AxRT"
name = "LionArt"
desc = "With the LionArt Crypto Token, we aim to create a sustainable funding model for artists and foster the growth of the digital art community."

[[TOKENS.WEBLINKS]]
url = "https://www.axrt.space"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.axrt.space/nft-gallery"
type = "website"
title = "Token Info Dashboard"
